version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: linux_small
      buildspec: build1.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
    - identifier: linux_medium
      buildspec: build2.yml
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
